=== BufferNihility/KeYmaeraX-release/keymaerax-webui/src/main/resources/js/schema/parentreply.json
{
  "$schema": "http://json-schema.org/schema#",
  "id": "http://keymaerax.org/schemas/parentreply.json",
  "title": "parentreply",
  "description": "The direct parent of a goal in the proof tree",
  "type": "object",
  "properties": {
    "id": {
      "type": "string",
      "description": "Identifies the parent in the proof tree"
    },
    "sequent": {
      "type": "object",
      "description": "See sequent.json (TODO: cross-reference schema)"
    },
    "children": {
      "type": "array",
      "description": "References to the children of this tree node",
      "uniqueItems": true,
      "items": {
        "type": "string",
        "description": "Identifies the child (ID)"
      }
    },
    "rule": {
      "type": "object",
      "description": "The proof rule that derived the children from this parent",
      "properties": {
        "id": {
          "type": "string",
          "description": "Identifies the proof rule"
        },
        "name": {
          "type": "string",
          "description": "Human-readable name of the proof rule"
        }
      },
      "required": ["id", "name"]
    },
    "parent": {
      "type": "string",
      "description": "The parent of this tree node, null if still needs to be loaded (default)."
    }
  },
  "required": ["id", "sequent", "children", "rule", "parent"]
}

=== BufferNihility/KeYmaeraX-release/keymaerax-webui/src/main/resources/mockdata/s-1parentreply.json
{
  "id": "S-2",
  "sequent": {
    "ante": [],
    "succ": [
      {
        "id": "F-2s",
        "formula": {
          "name": "imply",
          "id": "F-2s0",
          "children": [
            { "name": "lt", "id": "F-2s1", "children": [ {"name": "z", "id": "F-2s2"}, {"name": "1", "id": "F-2s3"} ] },
            {
              "name": "and", "id": "F-2s4",
              "children": [
                {
                  "name": "and", "id": "F-2s5",
                  "children": [
                    { "name": "lt", "id": "F-2s6", "children": [ {"name": "x", "id": "F-2s7"}, {"name": "5", "id": "F-2s8"} ] },
                    { "name": "true", "id": "F-2s9" }
                  ]
                },
                { "name": "gt", "id": "F-2s10", "children": [ {"name": "2", "id": "F-2s11"}, {"name": "y", "id": "F-2s12"} ] }
              ]
            }
          ]
        }
      }
    ]
  },
  "children": [ "S-1" ],
  "rule": { "id": "R0", "name": "skip" },
  "parent": "S-2"
}

=== BufferNihility/KeYmaeraX-release/keymaerax-webui/src/main/resources/mockdata/s5parentreply.json
{
  "id": "S4",
  "sequent": {
    "ante": [ {"id": "F4a", "formula": { "name": "lt", "id": "F4a0", "children": [ {"name": "z", "id": "F4a1"}, {"name": "1", "id": "F4a2"} ] }} ],
    "succ": [
      {
        "id": "F4s",
        "formula": {
          "name": "and",
          "id": "F4s0",
          "children": [
            { "name": "lt", "id": "F4s1", "children": [ {"name": "x", "id": "F4s2"}, {"name": "5", "id": "F4s3"} ] },
            { "name": "true", "id": "F4s4" }
          ]
        }
      }
    ]
  },
  "children": ["S5"],
  "rule": { "id": "R0", "name": "skip" },
  "parent": "S2"
}
